project = "my-flask-app-project"
database_user_password_secret_name = "DATABASE_USER_PASSWORD" 
flask_secret_key_secret_name = "FLASK_SECRET_KEY"
bucket_name = "blog_image_bucket_name"
database_name = "blog-database"
database_user_name = "blog-database-user"